### ISSUE TITLE
Make uniform retweet_count field

### ISSUE THREAD

**Issue by hmartos** [ekergy/tweemanager#14]
The field retweet_count of each document should be filled whether record is from getoldtweets or searchtweets as if record is from listener.

The practical approach we have tried is to perform an aggregation and an upsert, creating new tweets if the retweeted tweet does not exist in the db. The full code is better than an explanation (The code needs to be improved, this is justa a functional test):

``` javascript
db.tweem_default.aggregate([
	//{ $project : { "retweeted_status.id": 1, _id: 0 } },
        { $match: { "retweeted_status.id": {"$exists":true} }},
	{ $group : { _id: {"id":"$retweeted_status.id","texto":"$retweeted_status.text","screen_name":"$retweeted_status.user.screen_name","valoration":"$valoration.classifier1.value","created_at":"$retweeted_status.created_at"}, total: {$sum: 1}} },
        { $project : { "id": "$_id.id","tweet":"$_id.texto","retweets":"$total","link": {$concat: ["https://twitter.com/", "$_id.screen_name", "/status/", { $substr: [ "$_id.id", 0, -1 ]}]},"valoration": "$_id.valoration", "createdDateString": "$_id.created_at", _id:0 } },
	{ $sort: {retweets: -1}},
        { $limit: 12}
	], {cursor:{}}).forEach(function(doc) {
            print(doc.link);
//                 print doc;
                db.tweem_default.update(
                   {_id:doc.id},
                   {$set:{retweet_count:doc.retweets},"$setOnInsert":{'_id':doc.id,'verver':'verver'}},
                   { upsert: true }
                );
            }
          );
```

**Comment by cperales** [comment]
By the nature of listener, it can't take into account information about how many times a tweet has been retweeted. It listens always, even at the moment the tweet is initially published, so it detect de tweet, and the tweet go to the database.

I think a code like you may be implemented, in order to change database every time a new retweet is listened, but it makes the code slow, with many write access to database.
