### ISSUE TITLE
Configuration file should a JSON

### ISSUE THREAD

**Issue by hmartos** [ekergy/tweemanager#9]
Configuration file should be a JSON to make easier read and write files between Java and Python

**Comment by guillemborrell** [comment]
Or you can use ini4j.

**Comment by hmarrao** [comment]
or the https://github.com/ASzc/java-configparser project.
I'm Thinking in just add the json support to the configparser in parallel with the current ini file.

Also there is some bad programming in configparser since it is using eval to parse the array data like:

[TextPatterns]
patternstoexclude = ["cosas","España"]

I will change this to something like json.loads also.

**Comment by hmartos** [comment]
I have used both of them and have found that using [ini4j](http://ini4j.sourceforge.net/index.html) to handle configuration file is easier (in my opinion).
